### ISSUE TITLE
Resize images to match screen size

### ISSUE THREAD

**Issue by MarceloRuiz** [philer/MDModern#1]
I noticed that there is a scrollbar shown in MDM because blue.jpg and red.jpg are bigger than my screen resolution (1920x1080) and the image gets centered (so I see just a bit of the top bar). It would be great if the images could be stretched (reduced) to match the screen resolution and avoid the scrollbar.
Thanks for the great theme!

**Comment by philer** [comment]
There shouldn't be any scrollbars regardless of resolution. The background-image is set via css so it doesn't stretch anything.

One cause I could think of: Do you happen to have many languages installed? I.e. enough so the list in the dropdown under the language selection becomes higher then your screen?

**Comment by philer** [comment]
Was definitely the long lists. I pushed a fix.

**Comment by MarceloRuiz** [comment]
Hi, yes... weird, because I don't remember installing so many languages...
