### ISSUE TITLE
Does not handle network users

### ISSUE THREAD

**Issue by rbmj** [philer/MDModern#2]
The check here (js/mdm.js:87):

```
// additonal safeguard: only send passwords for known users
// (MDM's replies are kinda unpredictable otherwise)
if (mdm.getUser(user)) {
  if (debug) debug.log("MDM: sending username");
  alert("USER###" + user);
  userSelected = true;
}
else {
  trigger("error", 'User "' + user + '" doesn\'t exist!');
}
```

prevents network users from logging in, as it claims that the user doesn't exist.  Is there an alternate way to query if the user really exists/is mdm reliable enough (in recent versions) such that this check is no longer necessary?

**Comment by philer** [comment]
I built my js on the assumption that all users that are viable for login will be added via a function call by MDM. If that's not the case I'll have to change some stuff around.

As far as I know the way MDM responds to invalid login data hasn't changed and I still don't have a reliable grasp on what's happening in all possible cases (there is no documentation). I'll have to do some more digging.

Thanks for letting me know that this is an issue.

**Comment by rbmj** [comment]
Thanks for writing that lengthy post on the MDM tracker - hopefully they end up changing the API for the better (and adding documentation).  That can only make it easier for people to make new themes.

**Comment by philer** [comment]
I got some info on the IRC and was hopefully able to fix your issue. Feedback would be appreciated.
