### ISSUE TITLE
Support local language

### ISSUE THREAD

**Issue by DelPoint** [philer/MDModern#4]
Hi Philipp,

Firts of all: great greeter! One of the nicest on the web :+1: 
A small suggestion: would be much nicer if the greeter could extract the appropriate localized strings displayed on the screen - instead of using 'hard-wired' HTML tags (currently in English). These strings are: "Language", "Session", "Shutdown" etc. I'm not sure how to do this with HTML greeters, so I guess you are better position to evaulate the difficulty of this request.

Cheers,

Peter

**Comment by philer** [comment]
Hi,
thanks for your feedback!

Localization is definitely possible, in fact the MDM backend offers a method to do this. However it is a little weird to use, which is why I haven't tried it so far. I'll look into it when I have some time. ;)

**Comment by philer** [comment]
Done. I'll do some more testing and then merge it into my master branch and submit a pull request to linux mint's mdm themes repository. It might take a while until the changes are included so if you want to use it now you might have to install the theme manually from here.
