### ISSUE TITLE
Display background image based on the actual time

### ISSUE THREAD

**Issue by DelPoint** [philer/MDModern#5]
Hi Philipp,

Another suggestion - enhancement. It would be great if we could somehow control which background images are displayed on the login screen, based on what is the actual sytem time of the computer.
My idea would be: add some extra params into _slideshow.conf_ file. These params would be:
**morning_start = 05:00
day_start = 09:00
afternoon_start = 15:00
evening_start = 18:00
night_start = 09:00**

Each of the above params would define when a particular time of day begins considered by the user, using the hh:mm format.
Now, if we could add an extra 'tag' to the image path would define which image to display what time of day. Example:
**img/blue.jpg [morning]
img/red.jpg [day]**
_...etc._

Finally, the array and the display functions would be needed to amend according to this logic:
- if the actual time is between **morning_start** & **day_start** display only images tagged by **[morning]**
- if the actual time is between **day_start** & **afternoon_start** display only images tagged by **[day]**
  ...and so on, **but...**

_...all of the above would be optional, because if:_
- the settings (**morning_start**, **day_start**, etc.) for time of day are missing/incomplete
- or the _tagging_ of the images in the line of their path is missing:

> then: fall back to the current behaviour

On this way the greeter could be configured a little bit more 'sophisticated', reflecting the feelings of the actual time of day, displaying images only corresponding/reflecting to that 'feelings' :)

Cheers,

Peter

**Comment by philer** [comment]
I like the idea, but I don't think this is something a simple slideshow should be doing. I try to keep the modules' tasks as general as possible (I'm actually using it for another project as well) and this is a very specific use case.

However you can probably achieve this using something like cron or anacron or maybe an init.d script. Create several versions of your slideshow.conf file and then have them copied / symlinked according to day time (or even seasons). That way should be a lot more flexible.

**Comment by DelPoint** [comment]
> ...I don't think this is something a simple slideshow should be doing.

Yeah, if we think in terms of 'simple slideshow' :)

> ...and this is a very specific use case.

That's why I've written it as 'optional' enhancement.

> ...you can probably achieve this...

Me? Definitely not :( I'm not a programmer. MDM is totally new for me, my last (and most fresh) experiences/knowledge with *NIX like systems are dated back to 1995 - since I'm forced to work on Win. I've got an 12 years old desktop machine with Debian, and a laptop for my daughter with Linux Mint, I can sometimes recall my old UNIX (HP, VMS, Sun Solaris) capabilities just to figure out Linux is slightly different, but that's all. jQuery/JS: basically I've scratched their surface, I can 'distil' some results if I'm forced to do so, but it would definitely not reach the level & quality of your coding.

Anyway, thx. for your reply. If I come up with some genius solution (in the next 5-15 years) I'll send you a pull request :)

**Comment by philer** [comment]
I'm not talking about programming anything. Of course you could code this in javascript but what I meant is using regular Linux utilities to move some files around. [cron](https://en.wikipedia.org/wiki/Cron) and init.d are old as dust, in fact cron probably exists on any old UNIX as well.

Here are a few ideas on how to do it using those tools, though none of it is tested:
- Run `$ sudo crontab -e` to edit the global cron table with some text editor (usually vim or nano)
- Enter something along the lines of the following:

```
0 6 * * * cp /usr/share/mdm/html-themes/MDModern/morning-slideshow.conf /usr/share/mdm/html-themes/MDModern/slideshow.conf
0 18 * * * cp /usr/share/mdm/html-themes/MDModern/evening-slideshow.conf /usr/share/mdm/html-themes/MDModern/slideshow.conf
```

This will copy the respective config file for that time (in this example morning-slideshow.conf at 6:00 and evening-slideshow.conf at 18:00).

However these commands will only be executed if the computer is running at the given time.
You could create a little bash script and use init.d or upstart or /etc/rc.local to run it once immediately after booting. I haven't tried any of these so I don't know which of these is easiest to use but if you google “run script on startup” you'll find tons of help for that. The script could look something like this (again untested):

``` bash
#!/bin/bash
hour=$(date +%H)

if (( $hour < 6 ))
then
    theme="night"
elif (( $hour < 12 ))
then
    theme="morning"
elif (( $hour < 18 ))
then
    theme="afternoon"
else
    theme="night"
fi

cp "/usr/share/mdm/html-themes/MDModern/$theme-slideshow.conf" "/usr/share/mdm/html-themes/MDModern/slideshow.conf"

exit 0
```

I hope that helps.

**Comment by DelPoint** [comment]
It sounds reasonable. I'll try it if I'll have time to risk to demolish my current test system :) Thx. for the ideas.
